ALTER TABLE events
ADD COLUMN venue VARCHAR(255),
ADD COLUMN city VARCHAR(255),
ADD COLUMN date VARCHAR(50),
ADD COLUMN time VARCHAR(50),
ADD COLUMN image_url VARCHAR(1000),
ADD COLUMN ticket_url VARCHAR(1000),
Add COLUMN status VARCHAR(100);