spring.liquibase.contexts=dev
spring.liquibase.show-summary=summary

# Logging (development: verbose)
logging.level.com.notif.backend=DEBUG
logging.level.org.springframework.web=INFO
logging.level.org.springframework.cache.interceptor=TRACE
logging.pattern.console=%clr(%d{HH:mm:ss.SSS}){faint} %clr(%-5level) [%clr(%logger{0}){cyan}] - %msg%n